/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { HHDFaucet, HHDFaucetInterface } from "../HHDFaucet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "Token",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "token_HHD",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFreeToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103c63803806103c68339818101604052810190610032919061008d565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550506100ff565b600081519050610087816100e8565b92915050565b60006020828403121561009f57600080fd5b60006100ad84828501610078565b91505092915050565b60006100c1826100c8565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6100f1816100b6565b81146100fc57600080fd5b50565b6102b88061010e6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80639a954af91461003b578063e48ff02614610045575b600080fd5b610043610063565b005b61004d61011a565b60405161005a91906101d2565b60405180910390f35b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663a9059cbb33662386f26fc100006040518363ffffffff1660e01b81526004016100c59291906101a9565b602060405180830381600087803b1580156100df57600080fd5b505af11580156100f3573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101179190610153565b50565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60008151905061014d8161026b565b92915050565b60006020828403121561016557600080fd5b60006101738482850161013e565b91505092915050565b610185816101ed565b82525050565b61019481610235565b82525050565b6101a381610259565b82525050565b60006040820190506101be600083018561017c565b6101cb602083018461019a565b9392505050565b60006020820190506101e7600083018461018b565b92915050565b60006101f88261020b565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b600061024082610247565b9050919050565b60006102528261020b565b9050919050565b60006102648261022b565b9050919050565b610274816101ff565b811461027f57600080fd5b5056fea2646970667358221220769c844eded41fcafec35134cec77c96fd7159e951c016f47d23f659b2a05f0664736f6c63430008010033";

export class HHDFaucet__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    Token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<HHDFaucet> {
    return super.deploy(Token, overrides || {}) as Promise<HHDFaucet>;
  }
  getDeployTransaction(
    Token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(Token, overrides || {});
  }
  attach(address: string): HHDFaucet {
    return super.attach(address) as HHDFaucet;
  }
  connect(signer: Signer): HHDFaucet__factory {
    return super.connect(signer) as HHDFaucet__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HHDFaucetInterface {
    return new utils.Interface(_abi) as HHDFaucetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HHDFaucet {
    return new Contract(address, _abi, signerOrProvider) as HHDFaucet;
  }
}
